# Generated by Django 5.2.13 on 2026-05-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0004_alter_society_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(default='System', max_length=100)),
                ('actor_name', models.CharField(default='System', max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('complaint', 'Complaint'), ('resolve', 'Resolve'), ('assign', 'Assign'), ('publish', 'Publish'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('payment', 'Payment'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('target', models.CharField(max_length=500)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_audit_logs', to='platform_admin_create_society.society')),
            ],
            options={
                'verbose_name': 'Society Audit Log',
                'verbose_name_plural': 'Society Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['society', 'action_type'], name='saudit_soc_type_idx'), models.Index(fields=['society', 'created_at'], name='saudit_soc_time_idx')],
            },
        ),
    ]
