# Generated by Django 4.2.30 on 2026-05-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society_admin_flats', '0003_remove_flat_flat_building_number_uniq_alter_flat_id_and_more'),
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number_raw', models.CharField(blank=True, default='', help_text='Free-text flat number when flat FK is unknown.', max_length=50)),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('company', models.CharField(blank=True, default='', help_text='e.g. Amazon, Flipkart, Zomato, Swiggy', max_length=100)),
                ('delivery_type', models.CharField(choices=[('food', 'Food / Restaurant'), ('package', 'Package / Parcel'), ('courier', 'Courier / Express'), ('grocery', 'Grocery'), ('medicine', 'Medicine / Pharmacy'), ('flowers', 'Flowers / Gifts'), ('other', 'Other')], default='package', max_length=20)),
                ('package_desc', models.TextField(blank=True, default='', help_text='Brief package description.')),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved – Let In'), ('rejected', 'Rejected by Resident'), ('at_gate', 'Left at Gate'), ('collected', 'Collected by Resident'), ('returned', 'Returned to Sender')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('otp_code', models.CharField(blank=True, default='', max_length=6)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Guard/resident who approved the delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_approved', to='roles_permissions.userprofile')),
                ('collected_by', models.ForeignKey(blank=True, help_text='Resident profile who collected the at-gate package.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_collected', to='roles_permissions.userprofile')),
                ('flat', models.ForeignKey(blank=True, help_text='Linked flat record (preferred over flat_number_raw).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_entries', to='society_admin_flats.flat')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Guard who registered the delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_processed', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_entries', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-arrived_at'],
                'indexes': [models.Index(fields=['society'], name='deliv_society_idx'), models.Index(fields=['status'], name='deliv_status_idx'), models.Index(fields=['arrived_at'], name='deliv_arrived_idx'), models.Index(fields=['flat'], name='deliv_flat_idx')],
            },
        ),
    ]
