# Generated by Django 4.2.30 on 2026-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_guard_delivery_verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryentry',
            name='recipient_name',
            field=models.CharField(blank=True, default='', help_text='Resident name — person receiving the delivery', max_length=200),
        ),
        migrations.AddField(
            model_name='deliveryentry',
            name='tracking_id',
            field=models.CharField(blank=True, default='', help_text='Tracking number or order ID, e.g. AMZN-9876543', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryentry',
            name='vendor',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('swiggy', 'Swiggy'), ('zomato', 'Zomato'), ('bigbasket', 'BigBasket'), ('blinkit', 'Blinkit'), ('zepto', 'Zepto'), ('meesho', 'Meesho'), ('myntra', 'Myntra'), ('dunzo', 'Dunzo'), ('dtdc', 'DTDC Courier'), ('bluedart', 'Blue Dart'), ('delhivery', 'Delhivery'), ('india_post', 'India Post'), ('other', 'Other')], default='other', help_text='Vendor / app for dropdown selection', max_length=20),
        ),
    ]
