import os

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


def _proof_upload_path(instance, filename):
    """Upload to: media/statement_proofs/<society_id>/<stmt_id>/<filename>"""
    return os.path.join(
        "statement_proofs",
        str(instance.statement.society_id),
        str(instance.statement_id),
        filename,
    )


class MonthlyStatement(models.Model):
    """
    One statement per society per calendar month.

    Generated by the Society Admin from live MaintenanceDue + MaintenanceExpense
    data. Once published (is_published=True) it becomes visible to residents
    via the maintenance-transparency endpoint.
    """

    society = models.ForeignKey(
        "platform_admin_create_society.Society",
        on_delete=models.CASCADE,
        related_name="monthly_statements",
    )
    # First day of the billing month, e.g. 2026-05-01
    month = models.DateField(help_text="First day of the statement month.")

    # Financials — all computed at generation time and stored for immutability
    opening_balance  = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    total_collected  = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    total_expenses   = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    closing_balance  = models.DecimalField(max_digits=14, decimal_places=2, default=0)

    # Proof documents — snapshot of published expense proof URLs for this month
    proof_documents  = models.JSONField(
        default=list,
        help_text="List of proof document URLs from published expenses for this month.",
    )

    # Narrative summary auto-generated on save
    summary          = models.TextField(blank=True, default="")
    notes            = models.TextField(blank=True, default="")

    is_published  = models.BooleanField(default=False)
    published_at  = models.DateTimeField(null=True, blank=True)

    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="generated_statements",
    )
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

    class Meta:
        app_label       = "society_admin_monthly_statements"
        unique_together = [("society", "month")]
        ordering        = ["-month"]
        indexes         = [
            models.Index(fields=["society", "month"], name="stmt_society_month_idx"),
            models.Index(fields=["is_published"],     name="stmt_published_idx"),
        ]
        verbose_name        = "Monthly Statement"
        verbose_name_plural = "Monthly Statements"

    def __str__(self):
        return f"{self.society.name} — {self.month.strftime('%b %Y')}"

    # ── Computed helpers ───────────────────────────────────────────────────────

    @property
    def month_label(self) -> str:
        return self.month.strftime("%B %Y")

    @property
    def title(self) -> str:
        return f"{self.month_label} Maintenance Statement"


class StatementProofDocument(models.Model):
    """
    An uploaded PDF/image attached to a MonthlyStatement as proof.
    Society Admin can upload 1-10 files at a time via the upload-proof endpoint.
    """
    statement   = models.ForeignKey(
        MonthlyStatement,
        on_delete=models.CASCADE,
        related_name="uploaded_proofs",
    )
    file        = models.FileField(upload_to=_proof_upload_path)
    original_name = models.CharField(max_length=255)
    file_size   = models.PositiveIntegerField(default=0, help_text="File size in bytes.")
    uploaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="uploaded_proofs",
    )
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "society_admin_monthly_statements"
        ordering  = ["uploaded_at"]

    def __str__(self):
        return f"{self.statement} | {self.original_name}"

    @property
    def file_url(self) -> str:
        if self.file:
            return self.file.url
        return ""
