# Generated by Django 4.2.30 on 2026-05-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
        ('maintenance_staff_assigned_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_approved', to='roles_permissions.userprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_requested', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_requests', to='platform_admin_create_society.society')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_requests', to='maintenance_staff_assigned_tasks.maintenancetask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['society'], name='matreq_society_idx'), models.Index(fields=['status'], name='matreq_status_idx')],
            },
        ),
    ]
