# Generated by Django 5.2.13 on 2026-05-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('water_tanker', 'Water Tanker'), ('landscaping', 'Landscaping'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('security', 'Security Agency'), ('cleaning', 'Cleaning'), ('lift', 'Lift Maintenance'), ('pest', 'Pest Control'), ('other', 'Other')], max_length=20)),
                ('contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_renewal', 'Pending Renewal'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['society'], name='vendor_society_idx'), models.Index(fields=['status'], name='vendor_status_idx'), models.Index(fields=['category'], name='vendor_category_idx')],
            },
        ),
    ]
