# Generated by Django 5.2.13 on 2026-05-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
        ('roles_permissions', '0003_alter_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Gate 1 (Main), Gate 2 (Service)', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['society'], name='gate_society_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('unauthorized_vehicle', 'Unauthorized Vehicle'), ('tailgating', 'Tailgating Detected'), ('camera_offline', 'Camera Offline'), ('intrusion', 'Intrusion Attempt'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('gate', models.CharField(blank=True, default='', help_text='Gate where the alert was raised.', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=15)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['society'], name='alert_society_idx'), models.Index(fields=['status'], name='alert_status_idx'), models.Index(fields=['alert_type'], name='alert_type_idx')],
            },
        ),
    ]
