# Generated by Django 5.2.13 on 2026-05-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('security_guard', 'Security Guard'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('gardener', 'Gardener'), ('receptionist', 'Receptionist'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('other', 'Other')], max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Morning (06:00 – 14:00)'), ('day', 'Day (10:00 – 18:00)'), ('evening', 'Evening (14:00 – 22:00)'), ('night', 'Night (22:00 – 06:00)')], default='day', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=10)),
                ('gate_assigned', models.CharField(blank=True, default='', help_text='Gate name / number (for guards).', max_length=100)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['role', 'full_name'],
                'indexes': [models.Index(fields=['society'], name='staff_society_idx'), models.Index(fields=['role'], name='staff_role_idx'), models.Index(fields=['status'], name='staff_status_idx')],
            },
        ),
    ]
