# Generated by Django 4.2.30 on 2026-05-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='building',
            name='total_floors',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of floors in this building.'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
