# Generated by Django 5.2.13 on 2026-05-22 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_buildings', '0002_remove_building_building_society_name_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='building',
            name='building_society_name_uniq',
        ),
        migrations.RemoveField(
            model_name='building',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
