# Generated by Django 4.2.30 on 2026-05-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('entry_type', models.CharField(choices=[('visitor', 'Visitor'), ('delivery', 'Delivery'), ('vehicle', 'Vehicle Only'), ('staff', 'Staff'), ('resident', 'Resident'), ('other', 'Other')], default='visitor', max_length=20)),
                ('direction', models.CharField(choices=[('in', 'Entry'), ('out', 'Exit')], default='in', max_length=5)),
                ('flat_number', models.CharField(blank=True, default='', help_text='Destination / host flat', max_length=50)),
                ('purpose', models.TextField(blank=True, default='')),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries_processed', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_entries', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['society'], name='gentry_society_idx'), models.Index(fields=['entry_type'], name='gentry_type_idx'), models.Index(fields=['direction'], name='gentry_dir_idx'), models.Index(fields=['logged_at'], name='gentry_logged_idx')],
            },
        ),
    ]
