# Generated by Django 4.2.30 on 2026-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_guard_gate_entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateentry',
            name='gate',
            field=models.CharField(blank=True, default='', help_text='Gate where entry was processed, e.g. Gate 1 (Main)', max_length=100),
        ),
    ]
