# Generated by Django 4.2.30 on 2026-05-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('lift', 'Lift'), ('dispute', 'Dispute'), ('parking', 'Parking'), ('internet', 'Internet'), ('housekeeping', 'Housekeeping'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('app_issue', 'App Issue'), ('general', 'General'), ('other', 'Other')], default='general', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resident_name', models.CharField(blank=True, default='', max_length=200)),
                ('flat_number', models.CharField(blank=True, default='', max_length=50)),
                ('resident_phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_taken', models.CharField(blank=True, default='', max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_assigned', to='roles_permissions.userprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_created', to='roles_permissions.userprofile')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_raised', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_support_tickets', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['society'], name='sticket_society_idx'), models.Index(fields=['status'], name='sticket_status_idx'), models.Index(fields=['assigned_to'], name='sticket_assign_idx'), models.Index(fields=['priority'], name='sticket_priority_idx')],
            },
        ),
    ]
