# Generated by Django 5.2.13 on 2026-05-22 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0004_alter_society_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the statement month.')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('proof_documents', models.JSONField(default=list, help_text='List of proof document URLs from published expenses for this month.')),
                ('summary', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statements', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='platform_admin_create_society.society')),
            ],
            options={
                'verbose_name': 'Monthly Statement',
                'verbose_name_plural': 'Monthly Statements',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['society', 'month'], name='stmt_society_month_idx'), models.Index(fields=['is_published'], name='stmt_published_idx')],
                'unique_together': {('society', 'month')},
            },
        ),
    ]
