# Generated by Django 5.2.13 on 2026-05-22 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
        ('roles_permissions', '0001_initial'),
        ('society_admin_buildings', '0003_remove_building_building_society_name_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('notice', 'Notice'), ('event', 'Event'), ('fundraiser', 'Fundraiser'), ('maintenance', 'Maintenance Alert')], default='notice', max_length=20)),
                ('event_date', models.DateField(blank=True, help_text='Relevant date for events / maintenance windows.', null=True)),
                ('audience', models.CharField(choices=[('all', 'All Residents'), ('tower', 'Specific Tower'), ('owners', 'Owners Only'), ('custom', 'Custom Group')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('contribution_per_flat', models.DecimalField(blank=True, decimal_places=2, help_text='Amount expected from each flat (fundraisers only).', max_digits=10, null=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, help_text='Populated when audience=tower.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='society_admin_buildings.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='society_admin_notice_board.notice')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to='roles_permissions.userprofile')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['society'], name='notice_society_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['category'], name='notice_category_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['status'], name='notice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['audience'], name='notice_audience_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noticeread',
            unique_together={('notice', 'resident')},
        ),
    ]
