# Generated by Django 5.2.13 on 2026-05-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('society_admin_notice_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='society_admin_notice_board.noticeboard')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to='roles_permissions.userprofile')),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('notice', 'resident')},
            },
        ),
    ]
