# Generated by Django 5.2.13 on 2026-05-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='host_name',
            field=models.CharField(blank=True, default='', help_text='Resident being visited.', max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='photo_url',
            field=models.CharField(blank=True, default='', help_text='URL or path to visitor photo (uploaded by frontend).', max_length=500),
        ),
    ]
