# Generated by Django 5.2.13 on 2026-05-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_visitors', '0002_alter_visitor_host_name_alter_visitor_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='photo_url',
        ),
    ]
