# Generated by Django 5.2.13 on 2026-05-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
        ('roles_permissions', '0003_alter_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('security', 'Security Salary'), ('housekeeping', 'Housekeeping'), ('lift', 'Lift Maintenance'), ('water', 'Water Tanker'), ('electricity', 'Electricity'), ('gardening', 'Gardening'), ('repairs', 'Repairs'), ('insurance', 'Insurance'), ('administrative', 'Administrative'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=200)),
                ('proof_url', models.CharField(blank=True, default='', help_text='URL to invoice/receipt document.', max_length=500)),
                ('expense_date', models.DateField()),
                ('is_published', models.BooleanField(default=False, help_text='Published expenses are visible to residents.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_expenses', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['society'], name='expense_society_idx'), models.Index(fields=['category'], name='expense_category_idx'), models.Index(fields=['is_published'], name='expense_published_idx'), models.Index(fields=['expense_date'], name='expense_date_idx')],
            },
        ),
    ]
