# Generated by Django 4.2.30 on 2026-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_maintenance_expenses', '0002_expense_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceexpense',
            name='proof_url',
            field=models.CharField(blank=True, default='', help_text='URL or filename of invoice/receipt document.', max_length=500),
        ),
    ]
