# Generated by Django 5.2.13 on 2026-05-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_maintenance_expenses', '0003_alter_maintenanceexpense_proof_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceexpense',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Uploaded invoice/receipt PDF or image.', null=True, upload_to='expense_proofs/%Y/%m/'),
        ),
    ]
