# Generated by Django 4.2.30 on 2026-05-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sos', 'SOS / General Emergency'), ('fire', 'Fire'), ('medical', 'Medical Emergency'), ('intruder', 'Intruder / Unauthorized Entry'), ('theft', 'Theft / Vandalism'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_raised', to='roles_permissions.userprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['society'], name='emgalert_society_idx'), models.Index(fields=['status'], name='emgalert_status_idx'), models.Index(fields=['alert_type'], name='emgalert_type_idx'), models.Index(fields=['raised_at'], name='emgalert_raised_idx')],
            },
        ),
    ]
