# Generated by Django 4.2.30 on 2026-05-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_create_society', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='society',
            new_name='platform_ad_status_18d3bc_idx',
            old_name='platform_ad_status_idx',
        ),
        migrations.RenameIndex(
            model_name='society',
            new_name='platform_ad_plan_c7a85d_idx',
            old_name='platform_ad_plan_idx',
        ),
        migrations.RenameIndex(
            model_name='society',
            new_name='platform_ad_city_cff0f1_idx',
            old_name='platform_ad_city_idx',
        ),
    ]
