# Generated by Django 5.2.13 on 2026-05-22 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('platform_admin_create_society', '0002_rename_platform_ad_status_idx_platform_ad_status_18d3bc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='society',
            name='platform_ad_city_cff0f1_idx',
        ),
        migrations.AlterField(
            model_name='society',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='societies', to='accounts.city'),
        ),
        migrations.AddIndex(
            model_name='society',
            index=models.Index(fields=['city_id'], name='platform_ad_city_id_8aaead_idx'),
        ),
    ]
