# Generated by Django 5.2.13 on 2026-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
