# Generated by Django 5.2.13 on 2026-05-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_create_society', '0004_alter_society_status'),
        ('platform_admin_create_society', '0004_society_drop_city_name'),
    ]

    operations = [
    ]
