# Generated by Django 5.2.13 on 2026-05-22 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('platform_admin_create_society', '0005_merge_20260523_0258'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='society',
            name='platform_ad_city_id_8aaead_idx',
        ),
        migrations.AddIndex(
            model_name='society',
            index=models.Index(fields=['city'], name='platform_ad_city_id_8aaead_idx'),
        ),
    ]
