# Generated by Django 5.2.13 on 2026-05-22 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
        ('roles_permissions', '0002_alter_role_role_type'),
        ('society_admin_flats', '0003_remove_flat_flat_building_number_uniq_alter_flat_id_and_more'),
        ('society_admin_notice_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the billing month.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_dues', to='society_admin_flats.flat')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_dues', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='ResidentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('fundraiser', 'Fundraiser Contribution'), ('penalty', 'Penalty'), ('other', 'Other')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='upi', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='society_admin_flats.flat')),
                ('maintenance_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='resident_payments.maintenancedue')),
                ('notice', models.ForeignKey(blank=True, help_text='Populated for fundraiser contributions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='society_admin_notice_board.notice')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_payments', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancedue',
            index=models.Index(fields=['flat'], name='mdue_flat_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancedue',
            index=models.Index(fields=['society'], name='mdue_society_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancedue',
            index=models.Index(fields=['status'], name='mdue_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenancedue',
            unique_together={('flat', 'month')},
        ),
        migrations.AddIndex(
            model_name='residentpayment',
            index=models.Index(fields=['flat'], name='rpay_flat_idx'),
        ),
        migrations.AddIndex(
            model_name='residentpayment',
            index=models.Index(fields=['society'], name='rpay_society_idx'),
        ),
        migrations.AddIndex(
            model_name='residentpayment',
            index=models.Index(fields=['payment_type'], name='rpay_type_idx'),
        ),
    ]
