# Generated by Django 5.2.13 on 2026-05-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_payments', '0001_initial'),
        ('society_admin_notice_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentpayment',
            name='notice',
            field=models.ForeignKey(blank=True, help_text='Populated for fundraiser contributions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='society_admin_notice_board.noticeboard'),
        ),
    ]
