# Generated by Django 5.2.13 on 2026-05-22 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_approvals', '0001_initial'),
        ('society_admin_visitors', '0002_alter_visitor_host_name_alter_visitor_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Completion percentage 0–100.'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='visitor',
            field=models.OneToOneField(blank=True, help_text='Set when this approval was auto-created from a visitor entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval', to='society_admin_visitors.visitor'),
        ),
    ]
