# Generated by Django 5.2.13 on 2026-05-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_approvals', '0002_alter_approvalrequest_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='visitor',
        ),
    ]
