# Generated by Django 5.2.13 on 2026-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Matches Society.plan value (e.g. free, pro, enterprise).', unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_popular', models.BooleanField(default=False, help_text="Show 'Most Popular' badge.")),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_flats', models.PositiveIntegerField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('max_buildings', models.PositiveIntegerField(blank=True, null=True)),
                ('max_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(default=list, help_text='Array of feature strings, e.g. ["Visitor management", "24/7 support"]')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order (ascending).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price'],
                'indexes': [models.Index(fields=['slug'], name='plan_slug_idx'), models.Index(fields=['status'], name='plan_status_idx')],
            },
        ),
    ]
