# Generated by Django 5.2.13 on 2026-05-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_custom_pricing',
            field=models.BooleanField(default=False, help_text="If True, price shown as 'Custom' (contact sales). monthly_price is ignored for display."),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Mark this plan as a trial/free tier for KPI tracking.'),
        ),
    ]
