# Generated by Django 5.2.13 on 2026-05-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Administrative'), ('operational', 'Operational'), ('resident', 'Resident'), ('external', 'External')], default='operational', max_length=20),
        ),
    ]
