# Generated by Django 5.2.13 on 2026-05-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0002_alter_role_role_type'),
        ('roles_permissions', '0002_userprofile_created_by'),
        ('roles_permissions', '0003_alter_userprofile_status'),
    ]

    operations = [
    ]
