# Generated by Django 4.2.30 on 2026-05-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
        ('roles_permissions', '0004_merge_20260523_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRVerifyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.CharField(max_length=500)),
                ('full_name', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('is_valid', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_verify_logs', to='platform_admin_create_society.society')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_verify_logs', to='roles_permissions.userprofile')),
            ],
            options={
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['society', 'verified_at'], name='qrvlog_soc_time_idx')],
            },
        ),
    ]
