# Generated by Django 5.2.13 on 2026-05-22 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_buildings', '0003_remove_building_building_society_name_uniq_and_more'),
        ('society_admin_flats', '0002_remove_flat_flat_building_number_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flat',
            name='flat_building_number_uniq',
        ),
        migrations.AlterField(
            model_name='flat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('building', 'flat_number')},
        ),
    ]
