# Generated by Django 5.2.13 on 2026-05-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
        ('roles_permissions', '0002_alter_role_role_type'),
        ('society_admin_flats', '0003_remove_flat_flat_building_number_uniq_alter_flat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('security', 'Security'), ('noise', 'Noise'), ('parking', 'Parking'), ('cleanliness', 'Cleanliness'), ('amenities', 'Amenities'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='roles_permissions.userprofile')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='society_admin_flats.flat')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_complaints', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['society'], name='complaint_society_idx'), models.Index(fields=['status'], name='complaint_status_idx'), models.Index(fields=['category'], name='complaint_category_idx'), models.Index(fields=['resident'], name='complaint_resident_idx')],
            },
        ),
    ]
