# Generated by Django 5.2.13 on 2026-05-22 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
        ('roles_permissions', '0001_initial'),
        ('society_admin_notice_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('notif_type', models.CharField(choices=[('notice', 'Notice'), ('event', 'Event'), ('fundraiser', 'Fundraiser'), ('maintenance', 'Maintenance Alert'), ('system', 'System Message'), ('payment', 'Payment Reminder')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='society_admin_notice_board.notice')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='notif_recipient_idx'), models.Index(fields=['is_read'], name='notif_read_idx'), models.Index(fields=['notif_type'], name='notif_type_idx')],
            },
        ),
    ]
