# Generated by Django 5.2.13 on 2026-05-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_admin_notice_board', '0002_noticeread'),
        ('society_admin_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='society_admin_notice_board.noticeboard'),
        ),
    ]
