# Generated by Django 4.2.30 on 2026-05-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society_admin_flats', '0003_remove_flat_flat_building_number_uniq_alter_flat_id_and_more'),
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('auto', 'Auto Rickshaw'), ('bicycle', 'Bicycle'), ('other', 'Other')], default='car', max_length=20)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.CharField(choices=[('in', 'Entry'), ('out', 'Exit')], default='in', max_length=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_logs', to='society_admin_flats.flat')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_logs_processed', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_logs', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['society'], name='vlog_society_idx'), models.Index(fields=['vehicle_number'], name='vlog_number_idx'), models.Index(fields=['action'], name='vlog_action_idx'), models.Index(fields=['logged_at'], name='vlog_logged_idx')],
            },
        ),
    ]
