# Generated by Django 5.2.13 on 2026-05-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
        ('roles_permissions', '0003_alter_userprofile_status'),
        ('society_admin_flats', '0003_remove_flat_flat_building_number_uniq_alter_flat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('security', 'Security Threat'), ('medical', 'Medical Emergency'), ('fire', 'Fire'), ('other', 'Other Emergency')], default='other', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='society_admin_flats.flat')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='roles_permissions.userprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['society'], name='sos_society_idx'), models.Index(fields=['flat'], name='sos_flat_idx'), models.Index(fields=['status'], name='sos_status_idx'), models.Index(fields=['alert_type'], name='sos_type_idx')],
            },
        ),
    ]
