# Generated by Django 5.2.13 on 2026-05-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_permissions', '0002_alter_role_role_type'),
        ('society_admin_flats', '0003_remove_flat_flat_building_number_uniq_alter_flat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('visit_type', models.CharField(choices=[('guest', 'Guest'), ('delivery', 'Delivery'), ('cab', 'Cab / Taxi'), ('service', 'Service / Maintenance'), ('family', 'Family')], default='guest', max_length=20)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('pass_validity', models.CharField(choices=[('1h', '1 Hour'), ('4h', '4 Hours'), ('8h', '8 Hours'), ('24h', '24 Hours')], default='1h', max_length=5)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('notes_for_guard', models.TextField(blank=True, default='')),
                ('qr_code', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_passes', to='roles_permissions.userprofile')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_passes', to='society_admin_flats.flat')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flat'], name='gpass_flat_idx'), models.Index(fields=['status'], name='gpass_status_idx'), models.Index(fields=['visit_date'], name='gpass_date_idx')],
            },
        ),
    ]
