# Generated by Django 4.2.30 on 2026-05-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpass',
            name='pass_code',
            field=models.CharField(blank=True, default='', help_text='Human-readable pass code e.g. GW-7821-4403', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='visit_type',
            field=models.CharField(choices=[('personal', 'Personal Visit'), ('delivery', 'Delivery'), ('cab', 'Cab / Taxi'), ('service', 'Service / Maintenance'), ('family', 'Family')], default='personal', max_length=20),
        ),
    ]
