/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessIndexRouteImport } from './routes/access.index'
import { Route as AccessStatusRouteImport } from './routes/access.status'
import { Route as AccessQrRouteImport } from './routes/access.qr'
import { Route as AccessExpiredRouteImport } from './routes/access.expired'
import { Route as AppVisitorsRouteImport } from './routes/_app.visitors'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppResidentsIndexRouteImport } from './routes/_app.residents.index'
import { Route as AppSuperUsersRouteImport } from './routes/_app.super.users'
import { Route as AppSuperSubscriptionsRouteImport } from './routes/_app.super.subscriptions'
import { Route as AppSuperSocietyAdminsRouteImport } from './routes/_app.super.society-admins'
import { Route as AppSuperSettingsRouteImport } from './routes/_app.super.settings'
import { Route as AppSuperRolesRouteImport } from './routes/_app.super.roles'
import { Route as AppSuperReportsRouteImport } from './routes/_app.super.reports'
import { Route as AppSuperDashboardRouteImport } from './routes/_app.super.dashboard'
import { Route as AppSuperAuditRouteImport } from './routes/_app.super.audit'
import { Route as AppSocietyVendorsRouteImport } from './routes/_app.society.vendors'
import { Route as AppSocietyStaffRouteImport } from './routes/_app.society.staff'
import { Route as AppSocietyPaymentsRouteImport } from './routes/_app.society.payments'
import { Route as AppSocietyNoticesRouteImport } from './routes/_app.society.notices'
import { Route as AppSocietyMonthlyStatementsRouteImport } from './routes/_app.society.monthly-statements'
import { Route as AppSocietyMaintenanceFundsRouteImport } from './routes/_app.society.maintenance-funds'
import { Route as AppSocietyMaintenanceExpensesRouteImport } from './routes/_app.society.maintenance-expenses'
import { Route as AppSocietyFlatsRouteImport } from './routes/_app.society.flats'
import { Route as AppSocietyComplaintsRouteImport } from './routes/_app.society.complaints'
import { Route as AppSocietyBuildingsRouteImport } from './routes/_app.society.buildings'
import { Route as AppSocietyAuditRouteImport } from './routes/_app.society.audit'
import { Route as AppResidentsIdRouteImport } from './routes/_app.residents.$id'
import { Route as AppResidentVisitorsRouteImport } from './routes/_app.resident.visitors'
import { Route as AppResidentVehiclesRouteImport } from './routes/_app.resident.vehicles'
import { Route as AppResidentSosRouteImport } from './routes/_app.resident.sos'
import { Route as AppResidentProfileRouteImport } from './routes/_app.resident.profile'
import { Route as AppResidentPetsRouteImport } from './routes/_app.resident.pets'
import { Route as AppResidentPaymentsRouteImport } from './routes/_app.resident.payments'
import { Route as AppResidentNoticesRouteImport } from './routes/_app.resident.notices'
import { Route as AppResidentMaintenanceTransparencyRouteImport } from './routes/_app.resident.maintenance-transparency'
import { Route as AppResidentInviteRouteImport } from './routes/_app.resident.invite'
import { Route as AppResidentHomeRouteImport } from './routes/_app.resident.home'
import { Route as AppResidentHistoryRouteImport } from './routes/_app.resident.history'
import { Route as AppResidentHelpRouteImport } from './routes/_app.resident.help'
import { Route as AppResidentFamilyRouteImport } from './routes/_app.resident.family'
import { Route as AppResidentDeliveriesRouteImport } from './routes/_app.resident.deliveries'
import { Route as AppResidentDashboardRouteImport } from './routes/_app.resident.dashboard'
import { Route as AppResidentComplaintsRouteImport } from './routes/_app.resident.complaints'
import { Route as AppMaintenanceTasksRouteImport } from './routes/_app.maintenance.tasks'
import { Route as AppMaintenanceHistoryRouteImport } from './routes/_app.maintenance.history'
import { Route as AppMaintenanceDashboardRouteImport } from './routes/_app.maintenance.dashboard'
import { Route as AppGuardVisitorEntryRouteImport } from './routes/_app.guard.visitor-entry'
import { Route as AppGuardQrVerifyRouteImport } from './routes/_app.guard.qr-verify'
import { Route as AppGuardLogsRouteImport } from './routes/_app.guard.logs'
import { Route as AppGuardDeliveryVerifyRouteImport } from './routes/_app.guard.delivery-verify'
import { Route as AppGuardDashboardRouteImport } from './routes/_app.guard.dashboard'
import { Route as AppGuardContactRouteImport } from './routes/_app.guard.contact'
import { Route as AppGuardApprovedRouteImport } from './routes/_app.guard.approved'
import { Route as AppGuardAlertsRouteImport } from './routes/_app.guard.alerts'
import { Route as AppAdminRbacRouteImport } from './routes/_app.admin.rbac'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app.admin.analytics'
import { Route as AppAccountingTrackRouteImport } from './routes/_app.accounting.track'
import { Route as AppAccountingReportsRouteImport } from './routes/_app.accounting.reports'
import { Route as AppAccountingReceiptsRouteImport } from './routes/_app.accounting.receipts'
import { Route as AppAccountingGenerateRouteImport } from './routes/_app.accounting.generate'
import { Route as AppAccountingExportRouteImport } from './routes/_app.accounting.export'
import { Route as AppAccountingDuesRouteImport } from './routes/_app.accounting.dues'
import { Route as AppAccountingDashboardRouteImport } from './routes/_app.accounting.dashboard'
import { Route as AppSuperSocietiesIndexRouteImport } from './routes/_app.super.societies.index'
import { Route as AppSuperSocietiesNewRouteImport } from './routes/_app.super.societies.new'
import { Route as AppResidentExpensesIdRouteImport } from './routes/_app.resident.expenses.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessIndexRoute = AccessIndexRouteImport.update({
  id: '/access/',
  path: '/access/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessStatusRoute = AccessStatusRouteImport.update({
  id: '/access/status',
  path: '/access/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessQrRoute = AccessQrRouteImport.update({
  id: '/access/qr',
  path: '/access/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessExpiredRoute = AccessExpiredRouteImport.update({
  id: '/access/expired',
  path: '/access/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisitorsRoute = AppVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentsIndexRoute = AppResidentsIndexRouteImport.update({
  id: '/residents/',
  path: '/residents/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperUsersRoute = AppSuperUsersRouteImport.update({
  id: '/super/users',
  path: '/super/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperSubscriptionsRoute = AppSuperSubscriptionsRouteImport.update({
  id: '/super/subscriptions',
  path: '/super/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperSocietyAdminsRoute = AppSuperSocietyAdminsRouteImport.update({
  id: '/super/society-admins',
  path: '/super/society-admins',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperSettingsRoute = AppSuperSettingsRouteImport.update({
  id: '/super/settings',
  path: '/super/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperRolesRoute = AppSuperRolesRouteImport.update({
  id: '/super/roles',
  path: '/super/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperReportsRoute = AppSuperReportsRouteImport.update({
  id: '/super/reports',
  path: '/super/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperDashboardRoute = AppSuperDashboardRouteImport.update({
  id: '/super/dashboard',
  path: '/super/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAuditRoute = AppSuperAuditRouteImport.update({
  id: '/super/audit',
  path: '/super/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietyVendorsRoute = AppSocietyVendorsRouteImport.update({
  id: '/society/vendors',
  path: '/society/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietyStaffRoute = AppSocietyStaffRouteImport.update({
  id: '/society/staff',
  path: '/society/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietyPaymentsRoute = AppSocietyPaymentsRouteImport.update({
  id: '/society/payments',
  path: '/society/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietyNoticesRoute = AppSocietyNoticesRouteImport.update({
  id: '/society/notices',
  path: '/society/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietyMonthlyStatementsRoute =
  AppSocietyMonthlyStatementsRouteImport.update({
    id: '/society/monthly-statements',
    path: '/society/monthly-statements',
    getParentRoute: () => AppRoute,
  } as any)
const AppSocietyMaintenanceFundsRoute =
  AppSocietyMaintenanceFundsRouteImport.update({
    id: '/society/maintenance-funds',
    path: '/society/maintenance-funds',
    getParentRoute: () => AppRoute,
  } as any)
const AppSocietyMaintenanceExpensesRoute =
  AppSocietyMaintenanceExpensesRouteImport.update({
    id: '/society/maintenance-expenses',
    path: '/society/maintenance-expenses',
    getParentRoute: () => AppRoute,
  } as any)
const AppSocietyFlatsRoute = AppSocietyFlatsRouteImport.update({
  id: '/society/flats',
  path: '/society/flats',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietyComplaintsRoute = AppSocietyComplaintsRouteImport.update({
  id: '/society/complaints',
  path: '/society/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietyBuildingsRoute = AppSocietyBuildingsRouteImport.update({
  id: '/society/buildings',
  path: '/society/buildings',
  getParentRoute: () => AppRoute,
} as any)
const AppSocietyAuditRoute = AppSocietyAuditRouteImport.update({
  id: '/society/audit',
  path: '/society/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentsIdRoute = AppResidentsIdRouteImport.update({
  id: '/residents/$id',
  path: '/residents/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentVisitorsRoute = AppResidentVisitorsRouteImport.update({
  id: '/resident/visitors',
  path: '/resident/visitors',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentVehiclesRoute = AppResidentVehiclesRouteImport.update({
  id: '/resident/vehicles',
  path: '/resident/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentSosRoute = AppResidentSosRouteImport.update({
  id: '/resident/sos',
  path: '/resident/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentProfileRoute = AppResidentProfileRouteImport.update({
  id: '/resident/profile',
  path: '/resident/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentPetsRoute = AppResidentPetsRouteImport.update({
  id: '/resident/pets',
  path: '/resident/pets',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentPaymentsRoute = AppResidentPaymentsRouteImport.update({
  id: '/resident/payments',
  path: '/resident/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentNoticesRoute = AppResidentNoticesRouteImport.update({
  id: '/resident/notices',
  path: '/resident/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentMaintenanceTransparencyRoute =
  AppResidentMaintenanceTransparencyRouteImport.update({
    id: '/resident/maintenance-transparency',
    path: '/resident/maintenance-transparency',
    getParentRoute: () => AppRoute,
  } as any)
const AppResidentInviteRoute = AppResidentInviteRouteImport.update({
  id: '/resident/invite',
  path: '/resident/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentHomeRoute = AppResidentHomeRouteImport.update({
  id: '/resident/home',
  path: '/resident/home',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentHistoryRoute = AppResidentHistoryRouteImport.update({
  id: '/resident/history',
  path: '/resident/history',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentHelpRoute = AppResidentHelpRouteImport.update({
  id: '/resident/help',
  path: '/resident/help',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentFamilyRoute = AppResidentFamilyRouteImport.update({
  id: '/resident/family',
  path: '/resident/family',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentDeliveriesRoute = AppResidentDeliveriesRouteImport.update({
  id: '/resident/deliveries',
  path: '/resident/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentDashboardRoute = AppResidentDashboardRouteImport.update({
  id: '/resident/dashboard',
  path: '/resident/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentComplaintsRoute = AppResidentComplaintsRouteImport.update({
  id: '/resident/complaints',
  path: '/resident/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceTasksRoute = AppMaintenanceTasksRouteImport.update({
  id: '/maintenance/tasks',
  path: '/maintenance/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceHistoryRoute = AppMaintenanceHistoryRouteImport.update({
  id: '/maintenance/history',
  path: '/maintenance/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceDashboardRoute = AppMaintenanceDashboardRouteImport.update({
  id: '/maintenance/dashboard',
  path: '/maintenance/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardVisitorEntryRoute = AppGuardVisitorEntryRouteImport.update({
  id: '/guard/visitor-entry',
  path: '/guard/visitor-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardQrVerifyRoute = AppGuardQrVerifyRouteImport.update({
  id: '/guard/qr-verify',
  path: '/guard/qr-verify',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardLogsRoute = AppGuardLogsRouteImport.update({
  id: '/guard/logs',
  path: '/guard/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardDeliveryVerifyRoute = AppGuardDeliveryVerifyRouteImport.update({
  id: '/guard/delivery-verify',
  path: '/guard/delivery-verify',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardDashboardRoute = AppGuardDashboardRouteImport.update({
  id: '/guard/dashboard',
  path: '/guard/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardContactRoute = AppGuardContactRouteImport.update({
  id: '/guard/contact',
  path: '/guard/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardApprovedRoute = AppGuardApprovedRouteImport.update({
  id: '/guard/approved',
  path: '/guard/approved',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardAlertsRoute = AppGuardAlertsRouteImport.update({
  id: '/guard/alerts',
  path: '/guard/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRbacRoute = AppAdminRbacRouteImport.update({
  id: '/admin/rbac',
  path: '/admin/rbac',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingTrackRoute = AppAccountingTrackRouteImport.update({
  id: '/accounting/track',
  path: '/accounting/track',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingReportsRoute = AppAccountingReportsRouteImport.update({
  id: '/accounting/reports',
  path: '/accounting/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingReceiptsRoute = AppAccountingReceiptsRouteImport.update({
  id: '/accounting/receipts',
  path: '/accounting/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingGenerateRoute = AppAccountingGenerateRouteImport.update({
  id: '/accounting/generate',
  path: '/accounting/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingExportRoute = AppAccountingExportRouteImport.update({
  id: '/accounting/export',
  path: '/accounting/export',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingDuesRoute = AppAccountingDuesRouteImport.update({
  id: '/accounting/dues',
  path: '/accounting/dues',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingDashboardRoute = AppAccountingDashboardRouteImport.update({
  id: '/accounting/dashboard',
  path: '/accounting/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperSocietiesIndexRoute = AppSuperSocietiesIndexRouteImport.update({
  id: '/super/societies/',
  path: '/super/societies/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperSocietiesNewRoute = AppSuperSocietiesNewRouteImport.update({
  id: '/super/societies/new',
  path: '/super/societies/new',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentExpensesIdRoute = AppResidentExpensesIdRouteImport.update({
  id: '/resident/expenses/$id',
  path: '/resident/expenses/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/visitors': typeof AppVisitorsRoute
  '/access/expired': typeof AccessExpiredRoute
  '/access/qr': typeof AccessQrRoute
  '/access/status': typeof AccessStatusRoute
  '/access/': typeof AccessIndexRoute
  '/accounting/dashboard': typeof AppAccountingDashboardRoute
  '/accounting/dues': typeof AppAccountingDuesRoute
  '/accounting/export': typeof AppAccountingExportRoute
  '/accounting/generate': typeof AppAccountingGenerateRoute
  '/accounting/receipts': typeof AppAccountingReceiptsRoute
  '/accounting/reports': typeof AppAccountingReportsRoute
  '/accounting/track': typeof AppAccountingTrackRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/rbac': typeof AppAdminRbacRoute
  '/guard/alerts': typeof AppGuardAlertsRoute
  '/guard/approved': typeof AppGuardApprovedRoute
  '/guard/contact': typeof AppGuardContactRoute
  '/guard/dashboard': typeof AppGuardDashboardRoute
  '/guard/delivery-verify': typeof AppGuardDeliveryVerifyRoute
  '/guard/logs': typeof AppGuardLogsRoute
  '/guard/qr-verify': typeof AppGuardQrVerifyRoute
  '/guard/visitor-entry': typeof AppGuardVisitorEntryRoute
  '/maintenance/dashboard': typeof AppMaintenanceDashboardRoute
  '/maintenance/history': typeof AppMaintenanceHistoryRoute
  '/maintenance/tasks': typeof AppMaintenanceTasksRoute
  '/resident/complaints': typeof AppResidentComplaintsRoute
  '/resident/dashboard': typeof AppResidentDashboardRoute
  '/resident/deliveries': typeof AppResidentDeliveriesRoute
  '/resident/family': typeof AppResidentFamilyRoute
  '/resident/help': typeof AppResidentHelpRoute
  '/resident/history': typeof AppResidentHistoryRoute
  '/resident/home': typeof AppResidentHomeRoute
  '/resident/invite': typeof AppResidentInviteRoute
  '/resident/maintenance-transparency': typeof AppResidentMaintenanceTransparencyRoute
  '/resident/notices': typeof AppResidentNoticesRoute
  '/resident/payments': typeof AppResidentPaymentsRoute
  '/resident/pets': typeof AppResidentPetsRoute
  '/resident/profile': typeof AppResidentProfileRoute
  '/resident/sos': typeof AppResidentSosRoute
  '/resident/vehicles': typeof AppResidentVehiclesRoute
  '/resident/visitors': typeof AppResidentVisitorsRoute
  '/residents/$id': typeof AppResidentsIdRoute
  '/society/audit': typeof AppSocietyAuditRoute
  '/society/buildings': typeof AppSocietyBuildingsRoute
  '/society/complaints': typeof AppSocietyComplaintsRoute
  '/society/flats': typeof AppSocietyFlatsRoute
  '/society/maintenance-expenses': typeof AppSocietyMaintenanceExpensesRoute
  '/society/maintenance-funds': typeof AppSocietyMaintenanceFundsRoute
  '/society/monthly-statements': typeof AppSocietyMonthlyStatementsRoute
  '/society/notices': typeof AppSocietyNoticesRoute
  '/society/payments': typeof AppSocietyPaymentsRoute
  '/society/staff': typeof AppSocietyStaffRoute
  '/society/vendors': typeof AppSocietyVendorsRoute
  '/super/audit': typeof AppSuperAuditRoute
  '/super/dashboard': typeof AppSuperDashboardRoute
  '/super/reports': typeof AppSuperReportsRoute
  '/super/roles': typeof AppSuperRolesRoute
  '/super/settings': typeof AppSuperSettingsRoute
  '/super/society-admins': typeof AppSuperSocietyAdminsRoute
  '/super/subscriptions': typeof AppSuperSubscriptionsRoute
  '/super/users': typeof AppSuperUsersRoute
  '/residents/': typeof AppResidentsIndexRoute
  '/resident/expenses/$id': typeof AppResidentExpensesIdRoute
  '/super/societies/new': typeof AppSuperSocietiesNewRoute
  '/super/societies/': typeof AppSuperSocietiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/visitors': typeof AppVisitorsRoute
  '/access/expired': typeof AccessExpiredRoute
  '/access/qr': typeof AccessQrRoute
  '/access/status': typeof AccessStatusRoute
  '/access': typeof AccessIndexRoute
  '/accounting/dashboard': typeof AppAccountingDashboardRoute
  '/accounting/dues': typeof AppAccountingDuesRoute
  '/accounting/export': typeof AppAccountingExportRoute
  '/accounting/generate': typeof AppAccountingGenerateRoute
  '/accounting/receipts': typeof AppAccountingReceiptsRoute
  '/accounting/reports': typeof AppAccountingReportsRoute
  '/accounting/track': typeof AppAccountingTrackRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/rbac': typeof AppAdminRbacRoute
  '/guard/alerts': typeof AppGuardAlertsRoute
  '/guard/approved': typeof AppGuardApprovedRoute
  '/guard/contact': typeof AppGuardContactRoute
  '/guard/dashboard': typeof AppGuardDashboardRoute
  '/guard/delivery-verify': typeof AppGuardDeliveryVerifyRoute
  '/guard/logs': typeof AppGuardLogsRoute
  '/guard/qr-verify': typeof AppGuardQrVerifyRoute
  '/guard/visitor-entry': typeof AppGuardVisitorEntryRoute
  '/maintenance/dashboard': typeof AppMaintenanceDashboardRoute
  '/maintenance/history': typeof AppMaintenanceHistoryRoute
  '/maintenance/tasks': typeof AppMaintenanceTasksRoute
  '/resident/complaints': typeof AppResidentComplaintsRoute
  '/resident/dashboard': typeof AppResidentDashboardRoute
  '/resident/deliveries': typeof AppResidentDeliveriesRoute
  '/resident/family': typeof AppResidentFamilyRoute
  '/resident/help': typeof AppResidentHelpRoute
  '/resident/history': typeof AppResidentHistoryRoute
  '/resident/home': typeof AppResidentHomeRoute
  '/resident/invite': typeof AppResidentInviteRoute
  '/resident/maintenance-transparency': typeof AppResidentMaintenanceTransparencyRoute
  '/resident/notices': typeof AppResidentNoticesRoute
  '/resident/payments': typeof AppResidentPaymentsRoute
  '/resident/pets': typeof AppResidentPetsRoute
  '/resident/profile': typeof AppResidentProfileRoute
  '/resident/sos': typeof AppResidentSosRoute
  '/resident/vehicles': typeof AppResidentVehiclesRoute
  '/resident/visitors': typeof AppResidentVisitorsRoute
  '/residents/$id': typeof AppResidentsIdRoute
  '/society/audit': typeof AppSocietyAuditRoute
  '/society/buildings': typeof AppSocietyBuildingsRoute
  '/society/complaints': typeof AppSocietyComplaintsRoute
  '/society/flats': typeof AppSocietyFlatsRoute
  '/society/maintenance-expenses': typeof AppSocietyMaintenanceExpensesRoute
  '/society/maintenance-funds': typeof AppSocietyMaintenanceFundsRoute
  '/society/monthly-statements': typeof AppSocietyMonthlyStatementsRoute
  '/society/notices': typeof AppSocietyNoticesRoute
  '/society/payments': typeof AppSocietyPaymentsRoute
  '/society/staff': typeof AppSocietyStaffRoute
  '/society/vendors': typeof AppSocietyVendorsRoute
  '/super/audit': typeof AppSuperAuditRoute
  '/super/dashboard': typeof AppSuperDashboardRoute
  '/super/reports': typeof AppSuperReportsRoute
  '/super/roles': typeof AppSuperRolesRoute
  '/super/settings': typeof AppSuperSettingsRoute
  '/super/society-admins': typeof AppSuperSocietyAdminsRoute
  '/super/subscriptions': typeof AppSuperSubscriptionsRoute
  '/super/users': typeof AppSuperUsersRoute
  '/residents': typeof AppResidentsIndexRoute
  '/resident/expenses/$id': typeof AppResidentExpensesIdRoute
  '/super/societies/new': typeof AppSuperSocietiesNewRoute
  '/super/societies': typeof AppSuperSocietiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/visitors': typeof AppVisitorsRoute
  '/access/expired': typeof AccessExpiredRoute
  '/access/qr': typeof AccessQrRoute
  '/access/status': typeof AccessStatusRoute
  '/access/': typeof AccessIndexRoute
  '/_app/accounting/dashboard': typeof AppAccountingDashboardRoute
  '/_app/accounting/dues': typeof AppAccountingDuesRoute
  '/_app/accounting/export': typeof AppAccountingExportRoute
  '/_app/accounting/generate': typeof AppAccountingGenerateRoute
  '/_app/accounting/receipts': typeof AppAccountingReceiptsRoute
  '/_app/accounting/reports': typeof AppAccountingReportsRoute
  '/_app/accounting/track': typeof AppAccountingTrackRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/rbac': typeof AppAdminRbacRoute
  '/_app/guard/alerts': typeof AppGuardAlertsRoute
  '/_app/guard/approved': typeof AppGuardApprovedRoute
  '/_app/guard/contact': typeof AppGuardContactRoute
  '/_app/guard/dashboard': typeof AppGuardDashboardRoute
  '/_app/guard/delivery-verify': typeof AppGuardDeliveryVerifyRoute
  '/_app/guard/logs': typeof AppGuardLogsRoute
  '/_app/guard/qr-verify': typeof AppGuardQrVerifyRoute
  '/_app/guard/visitor-entry': typeof AppGuardVisitorEntryRoute
  '/_app/maintenance/dashboard': typeof AppMaintenanceDashboardRoute
  '/_app/maintenance/history': typeof AppMaintenanceHistoryRoute
  '/_app/maintenance/tasks': typeof AppMaintenanceTasksRoute
  '/_app/resident/complaints': typeof AppResidentComplaintsRoute
  '/_app/resident/dashboard': typeof AppResidentDashboardRoute
  '/_app/resident/deliveries': typeof AppResidentDeliveriesRoute
  '/_app/resident/family': typeof AppResidentFamilyRoute
  '/_app/resident/help': typeof AppResidentHelpRoute
  '/_app/resident/history': typeof AppResidentHistoryRoute
  '/_app/resident/home': typeof AppResidentHomeRoute
  '/_app/resident/invite': typeof AppResidentInviteRoute
  '/_app/resident/maintenance-transparency': typeof AppResidentMaintenanceTransparencyRoute
  '/_app/resident/notices': typeof AppResidentNoticesRoute
  '/_app/resident/payments': typeof AppResidentPaymentsRoute
  '/_app/resident/pets': typeof AppResidentPetsRoute
  '/_app/resident/profile': typeof AppResidentProfileRoute
  '/_app/resident/sos': typeof AppResidentSosRoute
  '/_app/resident/vehicles': typeof AppResidentVehiclesRoute
  '/_app/resident/visitors': typeof AppResidentVisitorsRoute
  '/_app/residents/$id': typeof AppResidentsIdRoute
  '/_app/society/audit': typeof AppSocietyAuditRoute
  '/_app/society/buildings': typeof AppSocietyBuildingsRoute
  '/_app/society/complaints': typeof AppSocietyComplaintsRoute
  '/_app/society/flats': typeof AppSocietyFlatsRoute
  '/_app/society/maintenance-expenses': typeof AppSocietyMaintenanceExpensesRoute
  '/_app/society/maintenance-funds': typeof AppSocietyMaintenanceFundsRoute
  '/_app/society/monthly-statements': typeof AppSocietyMonthlyStatementsRoute
  '/_app/society/notices': typeof AppSocietyNoticesRoute
  '/_app/society/payments': typeof AppSocietyPaymentsRoute
  '/_app/society/staff': typeof AppSocietyStaffRoute
  '/_app/society/vendors': typeof AppSocietyVendorsRoute
  '/_app/super/audit': typeof AppSuperAuditRoute
  '/_app/super/dashboard': typeof AppSuperDashboardRoute
  '/_app/super/reports': typeof AppSuperReportsRoute
  '/_app/super/roles': typeof AppSuperRolesRoute
  '/_app/super/settings': typeof AppSuperSettingsRoute
  '/_app/super/society-admins': typeof AppSuperSocietyAdminsRoute
  '/_app/super/subscriptions': typeof AppSuperSubscriptionsRoute
  '/_app/super/users': typeof AppSuperUsersRoute
  '/_app/residents/': typeof AppResidentsIndexRoute
  '/_app/resident/expenses/$id': typeof AppResidentExpensesIdRoute
  '/_app/super/societies/new': typeof AppSuperSocietiesNewRoute
  '/_app/super/societies/': typeof AppSuperSocietiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/approvals'
    | '/dashboard'
    | '/notifications'
    | '/security'
    | '/settings'
    | '/visitors'
    | '/access/expired'
    | '/access/qr'
    | '/access/status'
    | '/access/'
    | '/accounting/dashboard'
    | '/accounting/dues'
    | '/accounting/export'
    | '/accounting/generate'
    | '/accounting/receipts'
    | '/accounting/reports'
    | '/accounting/track'
    | '/admin/analytics'
    | '/admin/rbac'
    | '/guard/alerts'
    | '/guard/approved'
    | '/guard/contact'
    | '/guard/dashboard'
    | '/guard/delivery-verify'
    | '/guard/logs'
    | '/guard/qr-verify'
    | '/guard/visitor-entry'
    | '/maintenance/dashboard'
    | '/maintenance/history'
    | '/maintenance/tasks'
    | '/resident/complaints'
    | '/resident/dashboard'
    | '/resident/deliveries'
    | '/resident/family'
    | '/resident/help'
    | '/resident/history'
    | '/resident/home'
    | '/resident/invite'
    | '/resident/maintenance-transparency'
    | '/resident/notices'
    | '/resident/payments'
    | '/resident/pets'
    | '/resident/profile'
    | '/resident/sos'
    | '/resident/vehicles'
    | '/resident/visitors'
    | '/residents/$id'
    | '/society/audit'
    | '/society/buildings'
    | '/society/complaints'
    | '/society/flats'
    | '/society/maintenance-expenses'
    | '/society/maintenance-funds'
    | '/society/monthly-statements'
    | '/society/notices'
    | '/society/payments'
    | '/society/staff'
    | '/society/vendors'
    | '/super/audit'
    | '/super/dashboard'
    | '/super/reports'
    | '/super/roles'
    | '/super/settings'
    | '/super/society-admins'
    | '/super/subscriptions'
    | '/super/users'
    | '/residents/'
    | '/resident/expenses/$id'
    | '/super/societies/new'
    | '/super/societies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/approvals'
    | '/dashboard'
    | '/notifications'
    | '/security'
    | '/settings'
    | '/visitors'
    | '/access/expired'
    | '/access/qr'
    | '/access/status'
    | '/access'
    | '/accounting/dashboard'
    | '/accounting/dues'
    | '/accounting/export'
    | '/accounting/generate'
    | '/accounting/receipts'
    | '/accounting/reports'
    | '/accounting/track'
    | '/admin/analytics'
    | '/admin/rbac'
    | '/guard/alerts'
    | '/guard/approved'
    | '/guard/contact'
    | '/guard/dashboard'
    | '/guard/delivery-verify'
    | '/guard/logs'
    | '/guard/qr-verify'
    | '/guard/visitor-entry'
    | '/maintenance/dashboard'
    | '/maintenance/history'
    | '/maintenance/tasks'
    | '/resident/complaints'
    | '/resident/dashboard'
    | '/resident/deliveries'
    | '/resident/family'
    | '/resident/help'
    | '/resident/history'
    | '/resident/home'
    | '/resident/invite'
    | '/resident/maintenance-transparency'
    | '/resident/notices'
    | '/resident/payments'
    | '/resident/pets'
    | '/resident/profile'
    | '/resident/sos'
    | '/resident/vehicles'
    | '/resident/visitors'
    | '/residents/$id'
    | '/society/audit'
    | '/society/buildings'
    | '/society/complaints'
    | '/society/flats'
    | '/society/maintenance-expenses'
    | '/society/maintenance-funds'
    | '/society/monthly-statements'
    | '/society/notices'
    | '/society/payments'
    | '/society/staff'
    | '/society/vendors'
    | '/super/audit'
    | '/super/dashboard'
    | '/super/reports'
    | '/super/roles'
    | '/super/settings'
    | '/super/society-admins'
    | '/super/subscriptions'
    | '/super/users'
    | '/residents'
    | '/resident/expenses/$id'
    | '/super/societies/new'
    | '/super/societies'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/approvals'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/visitors'
    | '/access/expired'
    | '/access/qr'
    | '/access/status'
    | '/access/'
    | '/_app/accounting/dashboard'
    | '/_app/accounting/dues'
    | '/_app/accounting/export'
    | '/_app/accounting/generate'
    | '/_app/accounting/receipts'
    | '/_app/accounting/reports'
    | '/_app/accounting/track'
    | '/_app/admin/analytics'
    | '/_app/admin/rbac'
    | '/_app/guard/alerts'
    | '/_app/guard/approved'
    | '/_app/guard/contact'
    | '/_app/guard/dashboard'
    | '/_app/guard/delivery-verify'
    | '/_app/guard/logs'
    | '/_app/guard/qr-verify'
    | '/_app/guard/visitor-entry'
    | '/_app/maintenance/dashboard'
    | '/_app/maintenance/history'
    | '/_app/maintenance/tasks'
    | '/_app/resident/complaints'
    | '/_app/resident/dashboard'
    | '/_app/resident/deliveries'
    | '/_app/resident/family'
    | '/_app/resident/help'
    | '/_app/resident/history'
    | '/_app/resident/home'
    | '/_app/resident/invite'
    | '/_app/resident/maintenance-transparency'
    | '/_app/resident/notices'
    | '/_app/resident/payments'
    | '/_app/resident/pets'
    | '/_app/resident/profile'
    | '/_app/resident/sos'
    | '/_app/resident/vehicles'
    | '/_app/resident/visitors'
    | '/_app/residents/$id'
    | '/_app/society/audit'
    | '/_app/society/buildings'
    | '/_app/society/complaints'
    | '/_app/society/flats'
    | '/_app/society/maintenance-expenses'
    | '/_app/society/maintenance-funds'
    | '/_app/society/monthly-statements'
    | '/_app/society/notices'
    | '/_app/society/payments'
    | '/_app/society/staff'
    | '/_app/society/vendors'
    | '/_app/super/audit'
    | '/_app/super/dashboard'
    | '/_app/super/reports'
    | '/_app/super/roles'
    | '/_app/super/settings'
    | '/_app/super/society-admins'
    | '/_app/super/subscriptions'
    | '/_app/super/users'
    | '/_app/residents/'
    | '/_app/resident/expenses/$id'
    | '/_app/super/societies/new'
    | '/_app/super/societies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AccessExpiredRoute: typeof AccessExpiredRoute
  AccessQrRoute: typeof AccessQrRoute
  AccessStatusRoute: typeof AccessStatusRoute
  AccessIndexRoute: typeof AccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/': {
      id: '/access/'
      path: '/access'
      fullPath: '/access/'
      preLoaderRoute: typeof AccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/status': {
      id: '/access/status'
      path: '/access/status'
      fullPath: '/access/status'
      preLoaderRoute: typeof AccessStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/qr': {
      id: '/access/qr'
      path: '/access/qr'
      fullPath: '/access/qr'
      preLoaderRoute: typeof AccessQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/expired': {
      id: '/access/expired'
      path: '/access/expired'
      fullPath: '/access/expired'
      preLoaderRoute: typeof AccessExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/visitors': {
      id: '/_app/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AppVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/residents/': {
      id: '/_app/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof AppResidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/users': {
      id: '/_app/super/users'
      path: '/super/users'
      fullPath: '/super/users'
      preLoaderRoute: typeof AppSuperUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/subscriptions': {
      id: '/_app/super/subscriptions'
      path: '/super/subscriptions'
      fullPath: '/super/subscriptions'
      preLoaderRoute: typeof AppSuperSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/society-admins': {
      id: '/_app/super/society-admins'
      path: '/super/society-admins'
      fullPath: '/super/society-admins'
      preLoaderRoute: typeof AppSuperSocietyAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/settings': {
      id: '/_app/super/settings'
      path: '/super/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof AppSuperSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/roles': {
      id: '/_app/super/roles'
      path: '/super/roles'
      fullPath: '/super/roles'
      preLoaderRoute: typeof AppSuperRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/reports': {
      id: '/_app/super/reports'
      path: '/super/reports'
      fullPath: '/super/reports'
      preLoaderRoute: typeof AppSuperReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/dashboard': {
      id: '/_app/super/dashboard'
      path: '/super/dashboard'
      fullPath: '/super/dashboard'
      preLoaderRoute: typeof AppSuperDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/audit': {
      id: '/_app/super/audit'
      path: '/super/audit'
      fullPath: '/super/audit'
      preLoaderRoute: typeof AppSuperAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/vendors': {
      id: '/_app/society/vendors'
      path: '/society/vendors'
      fullPath: '/society/vendors'
      preLoaderRoute: typeof AppSocietyVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/staff': {
      id: '/_app/society/staff'
      path: '/society/staff'
      fullPath: '/society/staff'
      preLoaderRoute: typeof AppSocietyStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/payments': {
      id: '/_app/society/payments'
      path: '/society/payments'
      fullPath: '/society/payments'
      preLoaderRoute: typeof AppSocietyPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/notices': {
      id: '/_app/society/notices'
      path: '/society/notices'
      fullPath: '/society/notices'
      preLoaderRoute: typeof AppSocietyNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/monthly-statements': {
      id: '/_app/society/monthly-statements'
      path: '/society/monthly-statements'
      fullPath: '/society/monthly-statements'
      preLoaderRoute: typeof AppSocietyMonthlyStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/maintenance-funds': {
      id: '/_app/society/maintenance-funds'
      path: '/society/maintenance-funds'
      fullPath: '/society/maintenance-funds'
      preLoaderRoute: typeof AppSocietyMaintenanceFundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/maintenance-expenses': {
      id: '/_app/society/maintenance-expenses'
      path: '/society/maintenance-expenses'
      fullPath: '/society/maintenance-expenses'
      preLoaderRoute: typeof AppSocietyMaintenanceExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/flats': {
      id: '/_app/society/flats'
      path: '/society/flats'
      fullPath: '/society/flats'
      preLoaderRoute: typeof AppSocietyFlatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/complaints': {
      id: '/_app/society/complaints'
      path: '/society/complaints'
      fullPath: '/society/complaints'
      preLoaderRoute: typeof AppSocietyComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/buildings': {
      id: '/_app/society/buildings'
      path: '/society/buildings'
      fullPath: '/society/buildings'
      preLoaderRoute: typeof AppSocietyBuildingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/society/audit': {
      id: '/_app/society/audit'
      path: '/society/audit'
      fullPath: '/society/audit'
      preLoaderRoute: typeof AppSocietyAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/residents/$id': {
      id: '/_app/residents/$id'
      path: '/residents/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof AppResidentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/visitors': {
      id: '/_app/resident/visitors'
      path: '/resident/visitors'
      fullPath: '/resident/visitors'
      preLoaderRoute: typeof AppResidentVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/vehicles': {
      id: '/_app/resident/vehicles'
      path: '/resident/vehicles'
      fullPath: '/resident/vehicles'
      preLoaderRoute: typeof AppResidentVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/sos': {
      id: '/_app/resident/sos'
      path: '/resident/sos'
      fullPath: '/resident/sos'
      preLoaderRoute: typeof AppResidentSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/profile': {
      id: '/_app/resident/profile'
      path: '/resident/profile'
      fullPath: '/resident/profile'
      preLoaderRoute: typeof AppResidentProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/pets': {
      id: '/_app/resident/pets'
      path: '/resident/pets'
      fullPath: '/resident/pets'
      preLoaderRoute: typeof AppResidentPetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/payments': {
      id: '/_app/resident/payments'
      path: '/resident/payments'
      fullPath: '/resident/payments'
      preLoaderRoute: typeof AppResidentPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/notices': {
      id: '/_app/resident/notices'
      path: '/resident/notices'
      fullPath: '/resident/notices'
      preLoaderRoute: typeof AppResidentNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/maintenance-transparency': {
      id: '/_app/resident/maintenance-transparency'
      path: '/resident/maintenance-transparency'
      fullPath: '/resident/maintenance-transparency'
      preLoaderRoute: typeof AppResidentMaintenanceTransparencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/invite': {
      id: '/_app/resident/invite'
      path: '/resident/invite'
      fullPath: '/resident/invite'
      preLoaderRoute: typeof AppResidentInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/home': {
      id: '/_app/resident/home'
      path: '/resident/home'
      fullPath: '/resident/home'
      preLoaderRoute: typeof AppResidentHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/history': {
      id: '/_app/resident/history'
      path: '/resident/history'
      fullPath: '/resident/history'
      preLoaderRoute: typeof AppResidentHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/help': {
      id: '/_app/resident/help'
      path: '/resident/help'
      fullPath: '/resident/help'
      preLoaderRoute: typeof AppResidentHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/family': {
      id: '/_app/resident/family'
      path: '/resident/family'
      fullPath: '/resident/family'
      preLoaderRoute: typeof AppResidentFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/deliveries': {
      id: '/_app/resident/deliveries'
      path: '/resident/deliveries'
      fullPath: '/resident/deliveries'
      preLoaderRoute: typeof AppResidentDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/dashboard': {
      id: '/_app/resident/dashboard'
      path: '/resident/dashboard'
      fullPath: '/resident/dashboard'
      preLoaderRoute: typeof AppResidentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/complaints': {
      id: '/_app/resident/complaints'
      path: '/resident/complaints'
      fullPath: '/resident/complaints'
      preLoaderRoute: typeof AppResidentComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance/tasks': {
      id: '/_app/maintenance/tasks'
      path: '/maintenance/tasks'
      fullPath: '/maintenance/tasks'
      preLoaderRoute: typeof AppMaintenanceTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance/history': {
      id: '/_app/maintenance/history'
      path: '/maintenance/history'
      fullPath: '/maintenance/history'
      preLoaderRoute: typeof AppMaintenanceHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance/dashboard': {
      id: '/_app/maintenance/dashboard'
      path: '/maintenance/dashboard'
      fullPath: '/maintenance/dashboard'
      preLoaderRoute: typeof AppMaintenanceDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard/visitor-entry': {
      id: '/_app/guard/visitor-entry'
      path: '/guard/visitor-entry'
      fullPath: '/guard/visitor-entry'
      preLoaderRoute: typeof AppGuardVisitorEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard/qr-verify': {
      id: '/_app/guard/qr-verify'
      path: '/guard/qr-verify'
      fullPath: '/guard/qr-verify'
      preLoaderRoute: typeof AppGuardQrVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard/logs': {
      id: '/_app/guard/logs'
      path: '/guard/logs'
      fullPath: '/guard/logs'
      preLoaderRoute: typeof AppGuardLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard/delivery-verify': {
      id: '/_app/guard/delivery-verify'
      path: '/guard/delivery-verify'
      fullPath: '/guard/delivery-verify'
      preLoaderRoute: typeof AppGuardDeliveryVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard/dashboard': {
      id: '/_app/guard/dashboard'
      path: '/guard/dashboard'
      fullPath: '/guard/dashboard'
      preLoaderRoute: typeof AppGuardDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard/contact': {
      id: '/_app/guard/contact'
      path: '/guard/contact'
      fullPath: '/guard/contact'
      preLoaderRoute: typeof AppGuardContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard/approved': {
      id: '/_app/guard/approved'
      path: '/guard/approved'
      fullPath: '/guard/approved'
      preLoaderRoute: typeof AppGuardApprovedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guard/alerts': {
      id: '/_app/guard/alerts'
      path: '/guard/alerts'
      fullPath: '/guard/alerts'
      preLoaderRoute: typeof AppGuardAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/rbac': {
      id: '/_app/admin/rbac'
      path: '/admin/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AppAdminRbacRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/track': {
      id: '/_app/accounting/track'
      path: '/accounting/track'
      fullPath: '/accounting/track'
      preLoaderRoute: typeof AppAccountingTrackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/reports': {
      id: '/_app/accounting/reports'
      path: '/accounting/reports'
      fullPath: '/accounting/reports'
      preLoaderRoute: typeof AppAccountingReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/receipts': {
      id: '/_app/accounting/receipts'
      path: '/accounting/receipts'
      fullPath: '/accounting/receipts'
      preLoaderRoute: typeof AppAccountingReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/generate': {
      id: '/_app/accounting/generate'
      path: '/accounting/generate'
      fullPath: '/accounting/generate'
      preLoaderRoute: typeof AppAccountingGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/export': {
      id: '/_app/accounting/export'
      path: '/accounting/export'
      fullPath: '/accounting/export'
      preLoaderRoute: typeof AppAccountingExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/dues': {
      id: '/_app/accounting/dues'
      path: '/accounting/dues'
      fullPath: '/accounting/dues'
      preLoaderRoute: typeof AppAccountingDuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/dashboard': {
      id: '/_app/accounting/dashboard'
      path: '/accounting/dashboard'
      fullPath: '/accounting/dashboard'
      preLoaderRoute: typeof AppAccountingDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/societies/': {
      id: '/_app/super/societies/'
      path: '/super/societies'
      fullPath: '/super/societies/'
      preLoaderRoute: typeof AppSuperSocietiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super/societies/new': {
      id: '/_app/super/societies/new'
      path: '/super/societies/new'
      fullPath: '/super/societies/new'
      preLoaderRoute: typeof AppSuperSocietiesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resident/expenses/$id': {
      id: '/_app/resident/expenses/$id'
      path: '/resident/expenses/$id'
      fullPath: '/resident/expenses/$id'
      preLoaderRoute: typeof AppResidentExpensesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVisitorsRoute: typeof AppVisitorsRoute
  AppAccountingDashboardRoute: typeof AppAccountingDashboardRoute
  AppAccountingDuesRoute: typeof AppAccountingDuesRoute
  AppAccountingExportRoute: typeof AppAccountingExportRoute
  AppAccountingGenerateRoute: typeof AppAccountingGenerateRoute
  AppAccountingReceiptsRoute: typeof AppAccountingReceiptsRoute
  AppAccountingReportsRoute: typeof AppAccountingReportsRoute
  AppAccountingTrackRoute: typeof AppAccountingTrackRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminRbacRoute: typeof AppAdminRbacRoute
  AppGuardAlertsRoute: typeof AppGuardAlertsRoute
  AppGuardApprovedRoute: typeof AppGuardApprovedRoute
  AppGuardContactRoute: typeof AppGuardContactRoute
  AppGuardDashboardRoute: typeof AppGuardDashboardRoute
  AppGuardDeliveryVerifyRoute: typeof AppGuardDeliveryVerifyRoute
  AppGuardLogsRoute: typeof AppGuardLogsRoute
  AppGuardQrVerifyRoute: typeof AppGuardQrVerifyRoute
  AppGuardVisitorEntryRoute: typeof AppGuardVisitorEntryRoute
  AppMaintenanceDashboardRoute: typeof AppMaintenanceDashboardRoute
  AppMaintenanceHistoryRoute: typeof AppMaintenanceHistoryRoute
  AppMaintenanceTasksRoute: typeof AppMaintenanceTasksRoute
  AppResidentComplaintsRoute: typeof AppResidentComplaintsRoute
  AppResidentDashboardRoute: typeof AppResidentDashboardRoute
  AppResidentDeliveriesRoute: typeof AppResidentDeliveriesRoute
  AppResidentFamilyRoute: typeof AppResidentFamilyRoute
  AppResidentHelpRoute: typeof AppResidentHelpRoute
  AppResidentHistoryRoute: typeof AppResidentHistoryRoute
  AppResidentHomeRoute: typeof AppResidentHomeRoute
  AppResidentInviteRoute: typeof AppResidentInviteRoute
  AppResidentMaintenanceTransparencyRoute: typeof AppResidentMaintenanceTransparencyRoute
  AppResidentNoticesRoute: typeof AppResidentNoticesRoute
  AppResidentPaymentsRoute: typeof AppResidentPaymentsRoute
  AppResidentPetsRoute: typeof AppResidentPetsRoute
  AppResidentProfileRoute: typeof AppResidentProfileRoute
  AppResidentSosRoute: typeof AppResidentSosRoute
  AppResidentVehiclesRoute: typeof AppResidentVehiclesRoute
  AppResidentVisitorsRoute: typeof AppResidentVisitorsRoute
  AppResidentsIdRoute: typeof AppResidentsIdRoute
  AppSocietyAuditRoute: typeof AppSocietyAuditRoute
  AppSocietyBuildingsRoute: typeof AppSocietyBuildingsRoute
  AppSocietyComplaintsRoute: typeof AppSocietyComplaintsRoute
  AppSocietyFlatsRoute: typeof AppSocietyFlatsRoute
  AppSocietyMaintenanceExpensesRoute: typeof AppSocietyMaintenanceExpensesRoute
  AppSocietyMaintenanceFundsRoute: typeof AppSocietyMaintenanceFundsRoute
  AppSocietyMonthlyStatementsRoute: typeof AppSocietyMonthlyStatementsRoute
  AppSocietyNoticesRoute: typeof AppSocietyNoticesRoute
  AppSocietyPaymentsRoute: typeof AppSocietyPaymentsRoute
  AppSocietyStaffRoute: typeof AppSocietyStaffRoute
  AppSocietyVendorsRoute: typeof AppSocietyVendorsRoute
  AppSuperAuditRoute: typeof AppSuperAuditRoute
  AppSuperDashboardRoute: typeof AppSuperDashboardRoute
  AppSuperReportsRoute: typeof AppSuperReportsRoute
  AppSuperRolesRoute: typeof AppSuperRolesRoute
  AppSuperSettingsRoute: typeof AppSuperSettingsRoute
  AppSuperSocietyAdminsRoute: typeof AppSuperSocietyAdminsRoute
  AppSuperSubscriptionsRoute: typeof AppSuperSubscriptionsRoute
  AppSuperUsersRoute: typeof AppSuperUsersRoute
  AppResidentsIndexRoute: typeof AppResidentsIndexRoute
  AppResidentExpensesIdRoute: typeof AppResidentExpensesIdRoute
  AppSuperSocietiesNewRoute: typeof AppSuperSocietiesNewRoute
  AppSuperSocietiesIndexRoute: typeof AppSuperSocietiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVisitorsRoute: AppVisitorsRoute,
  AppAccountingDashboardRoute: AppAccountingDashboardRoute,
  AppAccountingDuesRoute: AppAccountingDuesRoute,
  AppAccountingExportRoute: AppAccountingExportRoute,
  AppAccountingGenerateRoute: AppAccountingGenerateRoute,
  AppAccountingReceiptsRoute: AppAccountingReceiptsRoute,
  AppAccountingReportsRoute: AppAccountingReportsRoute,
  AppAccountingTrackRoute: AppAccountingTrackRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminRbacRoute: AppAdminRbacRoute,
  AppGuardAlertsRoute: AppGuardAlertsRoute,
  AppGuardApprovedRoute: AppGuardApprovedRoute,
  AppGuardContactRoute: AppGuardContactRoute,
  AppGuardDashboardRoute: AppGuardDashboardRoute,
  AppGuardDeliveryVerifyRoute: AppGuardDeliveryVerifyRoute,
  AppGuardLogsRoute: AppGuardLogsRoute,
  AppGuardQrVerifyRoute: AppGuardQrVerifyRoute,
  AppGuardVisitorEntryRoute: AppGuardVisitorEntryRoute,
  AppMaintenanceDashboardRoute: AppMaintenanceDashboardRoute,
  AppMaintenanceHistoryRoute: AppMaintenanceHistoryRoute,
  AppMaintenanceTasksRoute: AppMaintenanceTasksRoute,
  AppResidentComplaintsRoute: AppResidentComplaintsRoute,
  AppResidentDashboardRoute: AppResidentDashboardRoute,
  AppResidentDeliveriesRoute: AppResidentDeliveriesRoute,
  AppResidentFamilyRoute: AppResidentFamilyRoute,
  AppResidentHelpRoute: AppResidentHelpRoute,
  AppResidentHistoryRoute: AppResidentHistoryRoute,
  AppResidentHomeRoute: AppResidentHomeRoute,
  AppResidentInviteRoute: AppResidentInviteRoute,
  AppResidentMaintenanceTransparencyRoute:
    AppResidentMaintenanceTransparencyRoute,
  AppResidentNoticesRoute: AppResidentNoticesRoute,
  AppResidentPaymentsRoute: AppResidentPaymentsRoute,
  AppResidentPetsRoute: AppResidentPetsRoute,
  AppResidentProfileRoute: AppResidentProfileRoute,
  AppResidentSosRoute: AppResidentSosRoute,
  AppResidentVehiclesRoute: AppResidentVehiclesRoute,
  AppResidentVisitorsRoute: AppResidentVisitorsRoute,
  AppResidentsIdRoute: AppResidentsIdRoute,
  AppSocietyAuditRoute: AppSocietyAuditRoute,
  AppSocietyBuildingsRoute: AppSocietyBuildingsRoute,
  AppSocietyComplaintsRoute: AppSocietyComplaintsRoute,
  AppSocietyFlatsRoute: AppSocietyFlatsRoute,
  AppSocietyMaintenanceExpensesRoute: AppSocietyMaintenanceExpensesRoute,
  AppSocietyMaintenanceFundsRoute: AppSocietyMaintenanceFundsRoute,
  AppSocietyMonthlyStatementsRoute: AppSocietyMonthlyStatementsRoute,
  AppSocietyNoticesRoute: AppSocietyNoticesRoute,
  AppSocietyPaymentsRoute: AppSocietyPaymentsRoute,
  AppSocietyStaffRoute: AppSocietyStaffRoute,
  AppSocietyVendorsRoute: AppSocietyVendorsRoute,
  AppSuperAuditRoute: AppSuperAuditRoute,
  AppSuperDashboardRoute: AppSuperDashboardRoute,
  AppSuperReportsRoute: AppSuperReportsRoute,
  AppSuperRolesRoute: AppSuperRolesRoute,
  AppSuperSettingsRoute: AppSuperSettingsRoute,
  AppSuperSocietyAdminsRoute: AppSuperSocietyAdminsRoute,
  AppSuperSubscriptionsRoute: AppSuperSubscriptionsRoute,
  AppSuperUsersRoute: AppSuperUsersRoute,
  AppResidentsIndexRoute: AppResidentsIndexRoute,
  AppResidentExpensesIdRoute: AppResidentExpensesIdRoute,
  AppSuperSocietiesNewRoute: AppSuperSocietiesNewRoute,
  AppSuperSocietiesIndexRoute: AppSuperSocietiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AccessExpiredRoute: AccessExpiredRoute,
  AccessQrRoute: AccessQrRoute,
  AccessStatusRoute: AccessStatusRoute,
  AccessIndexRoute: AccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
