# Generated by Django 5.2.13 on 2026-05-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_permissions', '0002_alter_role_role_type'),
        ('society_admin_flats', '0003_remove_flat_flat_building_number_uniq_alter_flat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('help_type', models.CharField(choices=[('maid', 'Maid'), ('cook', 'Cook'), ('driver', 'Driver'), ('watchman', 'Watchman'), ('other', 'Other')], max_length=20)),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_helpers', to='society_admin_flats.flat')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_helpers', to='roles_permissions.userprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('child', 'Child'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='society_admin_flats.flat')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='roles_permissions.userprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calling_name', models.CharField(blank=True, default='', max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='society_admin_flats.flat')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='roles_permissions.userprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('scooter', 'Scooter'), ('other', 'Other')], max_length=20)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('parking_slot', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='society_admin_flats.flat')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='roles_permissions.userprofile')),
            ],
            options={
                'ordering': ['vehicle_name'],
            },
        ),
    ]
