# Generated by Django 4.2.30 on 2026-05-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_profile', '0002_residentflat'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentflat',
            name='area',
            field=models.CharField(blank=True, default='', help_text="e.g. '1480 sq ft'", max_length=50),
        ),
        migrations.AddField(
            model_name='residentflat',
            name='facing',
            field=models.CharField(blank=True, default='', help_text="e.g. 'East', 'West', 'North', 'South'", max_length=20),
        ),
        migrations.AddField(
            model_name='residentflat',
            name='flat_type',
            field=models.CharField(blank=True, default='', help_text="e.g. '2 BHK', '3 BHK', 'Studio'", max_length=20),
        ),
        migrations.AddField(
            model_name='residentflat',
            name='floor',
            field=models.CharField(blank=True, default='', help_text="e.g. '3rd Floor'", max_length=50),
        ),
        migrations.AddField(
            model_name='residentflat',
            name='internet_connection',
            field=models.CharField(blank=True, default='', help_text="e.g. 'ACT Fibernet · 200 Mbps'", max_length=200),
        ),
        migrations.AddField(
            model_name='residentflat',
            name='parking_slots',
            field=models.CharField(blank=True, default='', help_text="e.g. 'P1-22 (Car) · B-07 (Bike)'", max_length=200),
        ),
        migrations.AddField(
            model_name='residentflat',
            name='power_connection',
            field=models.CharField(blank=True, default='', help_text="e.g. 'BESCOM · Meter No. 44821'", max_length=200),
        ),
        migrations.AddField(
            model_name='residentflat',
            name='resident_since',
            field=models.DateField(blank=True, help_text='Date the resident moved in.', null=True),
        ),
        migrations.AddField(
            model_name='residentflat',
            name='water_connection',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Borewell + BWSSB supply'", max_length=200),
        ),
    ]
