# Generated by Django 4.2.30 on 2026-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_profile', '0003_residentflat_area_residentflat_facing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Age in years.', null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='gate_access',
            field=models.BooleanField(default=False, help_text='Whether this family member has gate access.'),
        ),
    ]
