# Generated by Django 4.2.30 on 2026-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_profile', '0004_familymember_age_familymember_gate_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car_sedan', 'Car (Sedan)'), ('car_suv', 'Car (SUV)'), ('two_wheeler', 'Two-Wheeler'), ('other', 'Other')], max_length=20),
        ),
    ]
