# Generated by Django 4.2.30 on 2026-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_profile', '0006_pet_breed_vaccinated_optional_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhelp',
            name='days',
            field=models.CharField(blank=True, default='', help_text='e.g. Mon – Sat', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyhelp',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyhelp',
            name='timing',
            field=models.CharField(blank=True, default='', help_text='e.g. 07:00 – 10:00', max_length=50),
        ),
    ]
