# Generated by Django 4.2.30 on 2026-05-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('gate_assigned', models.CharField(blank=True, default='Main Gate', max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active / On Duty'), ('completed', 'Completed'), ('absent', 'Absent')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_shifts', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_shifts', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-shift_date', 'start_time'],
                'indexes': [models.Index(fields=['society', 'shift_date'], name='shift_soc_date_idx'), models.Index(fields=['guard'], name='shift_guard_idx'), models.Index(fields=['status'], name='shift_status_idx')],
            },
        ),
    ]
