# Generated by Django 5.2.13 on 2026-05-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin_create_society', '0003_remove_society_platform_ad_city_cff0f1_idx_and_more'),
        ('roles_permissions', '0003_alter_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('setup_fee', 'Setup Fee'), ('addon', 'Addon')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payment_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_payments', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_payments', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['society'], name='platpay_society_idx'), models.Index(fields=['payment_date'], name='platpay_date_idx'), models.Index(fields=['status'], name='platpay_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('billing', 'Billing'), ('feature_request', 'Feature Request'), ('account', 'Account'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_tickets', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='platform_admin_create_society.society')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['society'], name='ticket_society_idx'), models.Index(fields=['status'], name='ticket_status_idx')],
            },
        ),
    ]
