# Generated by Django 5.2.13 on 2026-05-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='platform_ad_society_8c7209_idx',
            old_name='platform_ad_society_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='platform_ad_payment_7bde96_idx',
            old_name='platform_ad_payment_date_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='platform_ad_status_c308c8_idx',
            old_name='platform_ad_status_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='platform_ad_status_9dbe46_idx',
            old_name='platform_ad_status_ticket_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='platform_ad_society_ab67bc_idx',
            old_name='platform_ad_society_ticket_idx',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='platform_admin_dashboard_platformpayment',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='platform_admin_dashboard_supportticket',
        ),
    ]
