# Generated by Django 4.2.30 on 2026-05-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_permissions', '0004_merge_20260523_0258'),
        ('platform_admin_create_society', '0007_remove_society_platform_ad_city_id_8aaead_idx_and_more'),
        ('maintenance_staff_assigned_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_schedules', to='roles_permissions.userprofile')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='platform_admin_create_society.society')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='maintenance_staff_assigned_tasks.maintenancetask')),
            ],
            options={
                'ordering': ['scheduled_date', 'start_time'],
                'indexes': [models.Index(fields=['society', 'scheduled_date'], name='msched_soc_date_idx'), models.Index(fields=['assigned_to'], name='msched_assign_idx')],
            },
        ),
    ]
