# Generated by Django 5.2.13 on 2026-05-22 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(default='Super Admin', max_length=100)),
                ('actor_name', models.CharField(default='System', max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('suspend', 'Suspend'), ('activate', 'Activate'), ('invite', 'Invite'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('target', models.CharField(max_length=500)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='platform_ad_action__7a7c68_idx'), models.Index(fields=['actor'], name='platform_ad_actor_i_fa249e_idx')],
            },
        ),
    ]
