# Generated by Django 5.2.13 on 2026-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin_audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text='e.g. USER_CREATED, SOCIETY_UPDATED', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_label',
            field=models.CharField(blank=True, default='', help_text='Denormalized actor name for display even after profile deletion.', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(blank=True, default='', help_text='e.g. Society, UserProfile', max_length=100),
        ),
    ]
